# spring.application.name=Productapp

# spring.datasource.url=jdbc:postgresql://dpg-d7au4tqli9vc73fj3j1g-a:5432/productdb_3c6w
# spring.datasource.username=productuser
# spring.datasource.password=FtwS0fcuvVMFqrXlwMAL0Dt93FL1lRmj

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# server.port=8080

spring.application.name=Productapp

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}